### ISSUE TITLE
Clarify origin of grass_modules_names.txt

### ISSUE THREAD

**Issue by wenzeslaus** [radeknovotny94/GRASS_Parse_to_QGIS_UI#3]
Make clear in README how the `grass_modules_names.txt` file was created and why it is included in the repository (e.g. as opposed to generated on the fly). Explain also the role of the file in the process.

**Comment by radeknovotny94** [comment]
Now it is generated on the fly through method - gcore.get_commands(). grass_modules_names.txt was deleted.
